//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proposition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proposition()
        {
            this.PropAccomodation = new HashSet<PropAccomodation>();
            this.PropExtraServices = new HashSet<PropExtraServices>();
            this.PropHallEquipment = new HashSet<PropHallEquipment>();
            this.PropMenuPosition = new HashSet<PropMenuPosition>();
            this.PropPaymentSuggestions = new HashSet<PropPaymentSuggestions>();
        }
    
        public int Id { get; set; }
        public int Id_user { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropAccomodation> PropAccomodation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropExtraServices> PropExtraServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropHallEquipment> PropHallEquipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropMenuPosition> PropMenuPosition { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropPaymentSuggestions> PropPaymentSuggestions { get; set; }
    }
}
