//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropMenuPosition
    {
        public int Id { get; set; }
        public Nullable<int> Id_proposition { get; set; }
        public string TypeOfService { get; set; }
        public Nullable<float> NettoPrice { get; set; }
        public Nullable<byte> Vat { get; set; }
        public Nullable<short> Amount { get; set; }
        public Nullable<short> Days { get; set; }
        public Nullable<decimal> Margin { get; set; }
    
        public virtual Proposition Proposition { get; set; }
    }
}
